function plotPSF()

    % Monkey to employ
    monkeyID = 'M838';

    simulatedCondition = 'AOSLO';

    % Stimulus params
    switch (simulatedCondition)
        case 'AOSLO'
            stimulusParams = simulator.params.AOSLOStimulus();
            opticsParams = struct(...
                'type', simulator.opticsTypes.diffractionLimited, ...
                'residualDefocusDiopters', 0.0, ...
                'pupilSizeMM', WilliamsLabData.constants.pupilDiameterMM, ...
                'wavelengthSupport', stimulusParams.wavelengthSupport);

        case 'AOSLOresidualDefocus'
            stimulusParams = simulator.params.AOSLOStimulus();
            opticsParams = struct(...
                'type', simulator.opticsTypes.diffractionLimited, ...
                'residualDefocusDiopters', 0.067, ...
                'pupilSizeMM', WilliamsLabData.constants.pupilDiameterMM, ...
                'wavelengthSupport', stimulusParams.wavelengthSupport);

        case 'CRT'
            stimulusParams = simulator.params.LCDAchromaticStimulus();
            opticsParams = struct(...
                'type', simulator.opticsTypes.M838, ...
                'pupilSizeMM', 3.0, ...
                'wavelengthSupport', stimulusParams.wavelengthSupport);

    end

    % Set the cone mosaic params
    cMosaicParams = struct(...
        'coneCouplingLambda', 0, ...
        'apertureShape', 'Gaussian', ...
        'apertureSigmaToDiameterRatio', 0.204, ...
        'integrationTimeSeconds', 5/1000, ...
        'wavelengthSupport', stimulusParams.wavelengthSupport);


    % Generate the optics for the examined condition
    [theOI, thePSFdata] = simulator.optics.generate(monkeyID, opticsParams);

    % Generate the cone mosaic
    theConeMosaic = simulator.coneMosaic.modify(monkeyID, cMosaicParams);
            

    hFig = figure(100); clf;
    set(hFig, 'Color', [1 1 1], 'Position', [10 10 300 300]);
    ax = subplot('Position', [0.19 0.16 0.78*0.7 0.83*0.7]);

    visualizedDomainRangeMicrons = 20;
    simulator.visualize.mosaicAndPSF(...
        theConeMosaic, thePSFdata, ...
        visualizedDomainRangeMicrons, WilliamsLabData.constants.imagingPeakWavelengthNM, ...
        'noConeMosaic', true, ...
        'figureHandle', hFig, ...
        'axesHandle', ax);
end