function frameStamps = frameTimeStamps(filename, dataLines)
%IMPORTFILE Import data from a text file
%  REF003206CDEG = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  REF003206CDEG = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ref003206cdeg = importfile("/Users/nicolas/Downloads/frame length data/Expt 1/838_20210105_ref_0032_06cdeg.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jun-2022 16:57:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "FRAME_INTERVALms", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "FRAME_INTERVALms";
opts.VariableTypes = ["string", "string", "string", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
frameTimeStampsTable = readtable(filename, opts);
frameStamps = table2array(frameTimeStampsTable);
frameStamps = frameStamps(2+(1:1479));
end