function pdfFilename = crossValidationSummaryFilename(modelVariant, ...
    centerConeType, startingPointsNum)

    % Generate data filename
    rootDirName = ISETmacaqueRootPath();


    transducerOptionsString = sprintf('transducerDC_%d_transducerSign_%d', ...
        modelVariant.transducerFunctionAccountsForResponseOffset, ...
        modelVariant.transducerFunctionAccountsForResponseSign);

    fitBiasString = sprintf('%sFitBias', modelVariant.fitBias);

        filename = fullfile(strrep(rootDirName, 'toolbox', ''), ...
                sprintf('simulations/generatedData/exports/CrossValidationSummary_%s_%s_%sCenterCone_coneCouplingLambda_%2.3f_%2.3fD_%s_multiStart%d', ...
                centerConeType, ...
                fitBiasString, ...
                modelVariant.centerConesSchema, ...
                modelVariant.coneCouplingLambda, ...
                modelVariant.residualDefocusDiopters, ...
                transducerOptionsString, ...
                startingPointsNum));

        pdfFilename = sprintf('%s.pdf', filename);

end