function [pdfFilename, videoFileName] = fitsPDFFilename(modelVariant, ...
    centerConeType, startingPointsNum, crossValidationRun, runType)
    % Generate data filename
    rootDirName = ISETmacaqueRootPath();

    if (crossValidationRun > 0)
        modelValidationString = sprintf('CrossValidated%sRun%d', runType, crossValidationRun);
    else
        modelValidationString = '';
    end

    filename = fullfile(strrep(rootDirName, 'toolbox', ''), ...
                sprintf('simulations/generatedData/exports/ISETBio%sFits_%sCenterConeNum_coneCouplingLambda_%2.3f_%2.3fD_%s_startingPoints%d', ...
                modelValidationString, ...
                modelVariant.centerConesNum, ...
                modelVariant.coneCouplingLambda, ...
                modelVariant.residualDefocusDiopters, ...
                centerConeType, startingPointsNum));

    pdfFilename = sprintf('%s.pdf', filename);
    videoFileName = sprintf('%s.mp4', filename);
end