function visualizeConeMosaicResponses(monkeyID, apertureParams, coneCouplingLambda, opticalDefocusDiopters, PolansSubject, visualStimulus)

    % Synthesize responses filename
    responseFileName = responsesFilename(monkeyID, apertureParams, coneCouplingLambda, opticalDefocusDiopters, PolansSubject, visualStimulus);
    
    load(responseFileName, 'theConeMosaic', 'coneMosaicBackgroundActivation', ...
        'coneMosaicSpatiotemporalActivation', 'temporalSupportSeconds', ...
        'examinedSpatialFrequencies');
    
    % Synthesize video filename
    switch (visualStimulus.type)
        case 'WilliamsLabStimulus'
            postFix = 'AOstimulus_MosaicResponses';
        case 'CRT'
            postFix = sprintf('LMS_%2.2f_%2.2f_%2.2fStimulus_MosaicResponses', visualStimulus.lmsConeContrasts(1), visualStimulus.lmsConeContrasts(2), visualStimulus.lmsConeContrasts(3));
    end
    videoFileName = videoFilename(monkeyID, apertureParams, coneCouplingLambda, opticalDefocusDiopters, ...
                PolansSubject, visualStimulus, 'MosaicResponses');
            
    videoOBJ = VideoWriter(videoFileName, 'MPEG-4');
    videoOBJ.FrameRate = 10;
    videoOBJ.Quality = 100;
    videoOBJ.open();
    
    activationRange = [min(coneMosaicSpatiotemporalActivation(:)) max(coneMosaicSpatiotemporalActivation(:))];
         
    hFig = figure(1);
    set(hFig, 'Position', [10 10 740 770]);
    ax = subplot('Position', [0.05 0.04 0.93 0.94]);
    for iSF = 1:numel(examinedSpatialFrequencies)
        
        % forward
        for phaseIndex = 1:numel(temporalSupportSeconds)
            theConeMosaic.visualize('figureHandle', hFig, ...
                'axesHandle', ax, ...
                'domain', 'microns', ...
                'domainVisualizationLimits', [-100 100 -100 100], ...
                'domainVisualizationTicks', struct('x', -10:10:10, 'y', -10:10:10), ...
                'visualizedConeAperture', 'geometricArea', ...
                'visualizedConeApertureThetaSamples', 60, ...
                'activation', squeeze(coneMosaicSpatiotemporalActivation(iSF,phaseIndex,:)),...
                'activationRange', activationRange, ...
                'backgroundColor', [0 0 0], ...
                'plotTitle', sprintf('%s (%2.1f c/deg)', strrep(postFix, '_', ' '), examinedSpatialFrequencies(iSF)));
            drawnow;
            videoOBJ.writeVideo(getframe(hFig));
        end
        % reverse
        for phaseIndex = numel(temporalSupportSeconds)-1:-1:1
            theConeMosaic.visualize('figureHandle', hFig, ...
                'axesHandle', ax, ...
                'domain', 'microns', ...
                'domainVisualizationLimits', [-100 100 -100 100], ...
                'domainVisualizationTicks', struct('x', -10:10:10, 'y', -10:10:10), ...
                'visualizedConeAperture', 'geometricArea', ...
                'visualizedConeApertureThetaSamples', 60, ...
                'activation', squeeze(coneMosaicSpatiotemporalActivation(iSF,phaseIndex,:)),...
                'activationRange', activationRange, ...
                'backgroundColor', [0 0 0], ...
                'plotTitle', sprintf('%2.1f c/deg', examinedSpatialFrequencies(iSF)));
            drawnow;
            videoOBJ.writeVideo(getframe(hFig));
        end
    end
    videoOBJ.close()
end

